version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: course_mongo_db
    restart: always
    ports:
      - "27017:27017"
    # NIJE definirano MONGO_INITDB_ROOT_USERNAME/PASSWORD — autenticacija je OFF

  mongo-express:
    image: mongo-express:latest
    container_name: course_mongo_gui
    restart: always
    ports:
      - "8081:8081"
    environment:
      # mongo‑express se povezuje bez user/pass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
